### ISSUE TITLE
Smaller blocks

### ISSUE THREAD

**Issue by tobyplowy** [LordStephen77/Minetest2D#1]
@LordStephen77 Now the player is 2 blocks tall is it possible to make it 3 or 4 this wuld allow you to add More detail to your Buildings and terrain

(like terraria [3 tall](https://s23.pixxxels.org/3wol356vf/terraria.jpg))
Or 
(like Starbound [4 tall](http://playstarbound.com/wp-content/uploads/2016/01/museum1.png))
I like 4 more

**Comment by LordStephen77** [comment]
Hi tobyplowy! Welcome here. The design has been completely rewritten, the textures have changed, and resembles much more Terraria rather than Minetest. I want to make it completely free and unique. For this reason in a short time, I will publish the project here on github with a different name.

Thanks for your interest. If you want to work on new graphic content, I'll send you some textures, bg game menu, and hotbar selectors tomorrow. Without obligation! This is a project for true enthusiasts! And will undergo significant improvements over time. I learn new things every day, and I use libGDX in the new project. This solution allows me to make the game available for Windows, Mac OS, Linux, Android and iOS available.

Thank you.

**Comment by tobyplowy** [comment]
@LordStephen77 how big is the player 3 blocks or 4?
Also I should say thank you for your amazing project

For textures can I make an issue, you post all textures that need to be done there I will work on it :)

Again thank you for your amazing project if you keep this much effort into this project you can make this something amazing!

**Comment by LordStephen77** [comment]
Yes, I'll send you all the textures just after I finish the last tweaks.

Thank you so much for your enthusiasm. This project is all about! I want to achieve something unique that is accessible to anyone. As time goes by, I will also increase my experience and I will improve many aspects.

I send you the first material as soon as I have the first working alpha. I just need to optimize some things.

Thanks friend.

**Comment by tobyplowy** [comment]
@LordStephen77 this can probably be closed

**Comment by tobyplowy** [comment]
@LordStephen77 shuld I make the issue for textures?

**Comment by LordStephen77** [comment]
@tobyplowy Yes, I wanted to put the label to keep it all in the archive in the future. I want to keep track of everything. Thanks friend.

**Comment by tobyplowy** [comment]
@LordStephen77 also when will the test build be available?

**Comment by LordStephen77** [comment]
@tobyplowy Update the repository in a few hours. Update readme.md with screenshots of the new project. Then I'll release the first build alpha in a few days. Time to work and to organize the starting point.

**Comment by tobyplowy** [comment]
can you show me a screenshot of the new blocks size (tiles) it will give me an idea of how to do the art style

Also Will you keep working on the project after the first alpha

**Comment by LordStephen77** [comment]
@tobyplowy Of course! I will work on this project over time, I'm not a student I'm 40 years old. I develop this game for passion. The first alpha serves only as a demo, then once the base of the gaming engine has ended, I will always include new improvements.

I forgot. The name of the repository and game will be changed in a few hours. So it will no longer be Minetest2D.
